export const authConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    REGISTER_REQUEST:'REGISTER_REQUEST',
    IS_USER_LOGGED_IN:"IS_USER_LOGGED_IN",
    LOGOUT_REQUEST:"LOGOUT_REQUEST"
}

export const todoConstants={
    ADD_TODO_REQUEST:"ADD_TODO_REQUEST",
    COMPLETE_TODO_REQUEST:"COMPLETE_TODO_REQUEST",
    
}